matching_groups:
  - ^/api/app/users$
  - ^/api/app/payment-methods$
  - ^/api/app/rides$
  - ^/api/app/rides/estimated-fare$
  - ^/api/app/rides/[^/]+/evaluation$
  - ^/api/app/notification$
  - ^/api/app/nearby-chairs$
  - ^/api/owner/owners$
  - ^/api/owner/sales$
  - ^/api/owner/chairs$
  - ^/api/chair/chairs$
  - ^/api/chair/activity$
  - ^/api/chair/coordinate$
  - ^/api/chair/notification$
  - ^/api/chair/rides/[^/]+/status$
  - ^/api/internal/matching$